class Locators():

    # register page objects
    first_name_css_selector = '[ng-model="FirstName"]'
    last_name_css_selector = '[ng-model="LastName"]'
    address_css_selector = '[ng-model="Adress"]'
    email_css_selector = '[ng-model="EmailAdress"]'
    phone_css_selector = '[ng-model="Phone"]'
    gender_male_css_selector = '[value="Male"]'
    gender_female_css_selector = '[value="FeMale"]'
    hobbies_cricket_class_name = 'Cricket'
    hobbies_movies_class_name = 'Movies'
    hobbies_hockey_class_name = 'Hockey'
    languages_id = 'msdd'
    skills_id = 'Skills'
    country_id = 'countries'
    select_country_id = 'select2-country-container'
    year_id = 'yearbox'
    month_css_selector = '[ng-init="monthbox"]'
    day_id = 'daybox'
    first_password_id = 'firstpassword'
    second_password_id = 'secondpassword'
    submit_button_id = 'submitbtn'
    refresh_button_id = 'Button1'